"""
Django settings for web_ui project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import json
import os
import shutil

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@b9idj_4skbcph+21q6^bc0qbs*$qs&@7r2sqfn*1#)z5_i%my'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Р”РѕРјРµРЅ Рё IP СЃРµСЂРІРµСЂР° вЂ” РїРѕ СѓРјРѕР»С‡Р°РЅРёСЋ, С‡С‚РѕР±С‹ СЂР°Р±РѕС‚Р°Р»Рѕ РїРѕ weuai.site Рё РїРѕ IP
_DEFAULT_ALLOWED = [
    "localhost",
    "127.0.0.1",
    "weuai.site",
    "www.weuai.site",
    "188.137.241.228",
]
ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "").split(",")
    if h.strip()
] or _DEFAULT_ALLOWED


# Application definition

INSTALLED_APPS = [
    'daphne',
    'core_ui',
    'tasks',
    'passwords',
    'servers',
    'agent_hub',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core_ui.middleware.AdminRussianMiddleware',
    'core_ui.middleware.MobileDetectionMiddleware',
]

ROOT_URLCONF = 'web_ui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core_ui' / 'templates',
            BASE_DIR / 'tasks' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core_ui.context_processors.app_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_ui.wsgi.application'
ASGI_APPLICATION = 'web_ui.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# MVP: PostgreSQL РґР»СЏ РєРѕРЅРєСѓСЂРµРЅС‚РЅРѕР№ СЂР°Р±РѕС‚С‹ (РјРЅРѕРіРѕ Р°РіРµРЅС‚РѕРІ/РІРѕСЂРєРµСЂРѕРІ Р±РµР· Р±Р»РѕРєРёСЂРѕРІРѕРє SQLite).
# Р—Р°РґР°Р№С‚Рµ POSTGRES_HOST (РёР»Рё POSTGRES_DB) РІ .env вЂ” Р±СѓРґРµС‚ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊСЃСЏ PostgreSQL.
# РРЅР°С‡Рµ вЂ” SQLite РґР»СЏ Р»РѕРєР°Р»СЊРЅРѕРіРѕ СЃС‚Р°СЂС‚Р° Р±РµР· Docker.

def _get_database_config():
    use_postgres = os.getenv("POSTGRES_HOST") or os.getenv("POSTGRES_DB")
    if use_postgres:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "weu_platform"),
            "USER": os.getenv("POSTGRES_USER", "weu"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": 60,  # РїРµСЂРµРёСЃРїРѕР»СЊР·РѕРІР°РЅРёРµ СЃРѕРµРґРёРЅРµРЅРёР№ РїСЂРё РЅР°РіСЂСѓР·РєРµ
            "OPTIONS": {
                "connect_timeout": 10,
                "options": "-c statement_timeout=30000",  # 30s РјР°РєСЃ. РЅР° Р·Р°РїСЂРѕСЃ
            },
        }
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }


DATABASES = {"default": _get_database_config()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core_ui' / 'static',
]

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
UPLOADED_FILES_DIR = MEDIA_ROOT / 'uploads'

# Create upload directory if it doesn't exist
UPLOADED_FILES_DIR.mkdir(parents=True, exist_ok=True)

# Agent projects directory
AGENT_PROJECTS_DIR = BASE_DIR / 'agent_projects'
AGENT_PROJECTS_DIR.mkdir(parents=True, exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# CLI runtime timeout (РѕР±С‰РёР№ Р»РёРјРёС‚ РІСЂРµРјРµРЅРё СЂР°Р±РѕС‚С‹ РїСЂРѕС†РµСЃСЃР°)
CLI_RUNTIME_TIMEOUT_SECONDS = int(os.getenv("CLI_RUNTIME_TIMEOUT_SECONDS", "600"))

# РўР°Р№РјР°СѓС‚ В«РїРµСЂРІРѕРіРѕ РІС‹РІРѕРґР°В»: РµСЃР»Рё Claude РЅРµ РІС‹РІРµР» РЅРё РѕРґРЅРѕР№ СЃС‚СЂРѕРєРё Р·Р° СЌС‚Рѕ РІСЂРµРјСЏ вЂ” РїСЂРµСЂРІР°С‚СЊ.
# РћР±С‹С‡РЅРѕ РѕР·РЅР°С‡Р°РµС‚, С‡С‚Рѕ Claude Р¶РґС‘С‚ MCP-СЃРµСЂРІРµСЂ, РєРѕС‚РѕСЂС‹Р№ РЅРµ Р·Р°РїСѓСЃС‚РёР»СЃСЏ РёР»Рё Р·Р°РІРёСЃ РїСЂРё СЃС‚Р°СЂС‚Рµ Django.
CLI_FIRST_OUTPUT_TIMEOUT_SECONDS = int(os.getenv("CLI_FIRST_OUTPUT_TIMEOUT_SECONDS", "120"))

# РџРµСЂРµРґ Р·Р°РїСѓСЃРєРѕРј С‚Р°СЃРєР°/РІРѕСЂРєС„Р»РѕСѓ СЃРЅР°С‡Р°Р»Р° РїСЂРѕРІРµСЂРёС‚СЊ Р·Р°РґР°С‡Сѓ С‡РµСЂРµР· Cursor (--mode=ask). Р•СЃР»Рё True вЂ” С„Р°Р·Р° В«Р°РЅР°Р»РёР·В» РїРµСЂРµРґ РІС‹РїРѕР»РЅРµРЅРёРµРј.
ANALYZE_TASK_BEFORE_RUN = os.getenv("ANALYZE_TASK_BEFORE_RUN", "1").strip().lower() in ("1", "true", "yes", "on")

# Cursor CLI: HTTP/1 mode (default on) to avoid proxy/VPN issues when HTTP/2 is blocked.
# Override: CURSOR_CLI_HTTP_1=0 or false to disable.
_raw_http1 = os.getenv("CURSOR_CLI_HTTP_1", "1").strip().lower()
CURSOR_CLI_HTTP_1 = _raw_http1 not in ("0", "false", "no", "off")


def _parse_cursor_cli_extra_env():
    """Extra env vars for Cursor CLI. When CURSOR_CLI_HTTP_1 is True, adds CURSOR_DISABLE_HTTP2=1.
    CURSOR_API_KEY (РѕС‚РґРµР»СЊРЅРѕ РІ .env) вЂ” headless-РІС…РѕРґ Р±РµР· Google; РєР»СЋС‡ РІ Cursor в†’ Settings в†’ API Access.
    Override via CURSOR_CLI_EXTRA_ENV JSON, e.g. CURSOR_CLI_EXTRA_ENV='{"KEY":"VALUE"}'."""
    raw = os.getenv("CURSOR_CLI_EXTRA_ENV", "").strip()
    if raw:
        try:
            d = json.loads(raw)
            return dict(d) if isinstance(d, dict) else {}
        except json.JSONDecodeError:
            return {}
    if CURSOR_CLI_HTTP_1:
        return {"CURSOR_DISABLE_HTTP2": "1"}
    return {}


CURSOR_CLI_EXTRA_ENV = _parse_cursor_cli_extra_env()

# CLI runtime configuration for external agents
def _cli_command(env_var: str, default_name: str) -> str:
    return os.getenv(env_var) or shutil.which(default_name) or default_name


# Р”РѕСЃС‚СѓРїРЅС‹Рµ РјРѕРґРµР»Рё Cursor CLI (Р°РєС‚СѓР°Р»СЊРЅС‹Р№ СЃРїРёСЃРѕРє РїРѕ РґРѕРєСѓРјРµРЅС‚Р°С†РёРё Cursor, Р±РµР· Max Mode)
# РСЃС‚РѕС‡РЅРёРє: https://docs.cursor.com/models
CURSOR_AVAILABLE_MODELS = [
    {"id": "auto", "name": "Auto", "description": "РђРІС‚РѕРјР°С‚РёС‡РµСЃРєРёР№ РІС‹Р±РѕСЂ Р»СѓС‡С€РµР№ РјРѕРґРµР»Рё"},
    {"id": "claude-4.5-sonnet", "name": "Claude 4.5 Sonnet", "description": "РЎР±Р°Р»Р°РЅСЃРёСЂРѕРІР°РЅРЅР°СЏ, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "claude-4.5-opus", "name": "Claude 4.5 Opus", "description": "РЎР°РјР°СЏ РјРѕС‰РЅР°СЏ, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gpt-5.2", "name": "GPT-5.2", "description": "OpenAI, 272k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gpt-5.2-codex", "name": "GPT-5.2 Codex", "description": "OpenAI Codex, 272k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gemini-3-flash", "name": "Gemini 3 Flash", "description": "Google, Р±С‹СЃС‚СЂР°СЏ, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "gemini-3-pro", "name": "Gemini 3 Pro", "description": "Google Pro, 200k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "grok-code", "name": "Grok Code", "description": "xAI, 256k РєРѕРЅС‚РµРєСЃС‚"},
    {"id": "composer-1", "name": "Composer 1", "description": "Cursor native, 200k РєРѕРЅС‚РµРєСЃС‚"},
]

# Р РµРєРѕРјРµРЅРґР°С†РёРё РјРѕРґРµР»РµР№ РїРѕ С‚РёРїСѓ Р·Р°РґР°С‡Рё (РёСЃРїРѕР»СЊР·СѓРµС‚СЃСЏ SmartTaskAnalyzer)
MODEL_RECOMMENDATIONS = {
    "simple": "gemini-3-flash",       # Р РµС„Р°РєС‚РѕСЂРёРЅРі, lint-fix, С„РѕСЂРјР°С‚РёСЂРѕРІР°РЅРёРµ - Р±С‹СЃС‚СЂР°СЏ РјРѕРґРµР»СЊ
    "standard": "claude-4.5-sonnet",  # РќРѕРІС‹Р№ РєРѕРґ, С„РёС‡Рё, СЃС‚Р°РЅРґР°СЂС‚РЅС‹Рµ Р·Р°РґР°С‡Рё
    "complex": "claude-4.5-opus",     # РђСЂС…РёС‚РµРєС‚СѓСЂР°, РґРёР·Р°Р№РЅ, СЃР»РѕР¶РЅР°СЏ Р»РѕРіРёРєР°
    "debug": "gpt-5.2",               # Р”РµР±Р°Рі, Р°РЅР°Р»РёР· РѕС€РёР±РѕРє
}


CLI_RUNTIME_CONFIG = {
    "cursor": {
        "command": _cli_command("CURSOR_CLI_PATH", "agent"),
        # --force: Р°РіРµРЅС‚ РјРѕР¶РµС‚ РјРµРЅСЏС‚СЊ С„Р°Р№Р»С‹ Р±РµР· РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ
        # --output-format stream-json: СЃС‚СЂРёРјРёРЅРі РґР»СЏ РґРµС‚Р°Р»СЊРЅС‹С… Р»РѕРіРѕРІ РїРѕ С€Р°РіР°Рј
        # --stream-partial-output: РїСЂРѕРіСЂРµСЃСЃ РїРѕ С€Р°РіР°Рј
        # РњРѕРґРµР»СЊ С‚РµРїРµСЂСЊ РїРµСЂРµРґР°С‘С‚СЃСЏ РґРёРЅР°РјРёС‡РµСЃРєРё С‡РµСЂРµР· allowed_args
        "args": ["-p", "--force", "--output-format", "stream-json", "--stream-partial-output", "--workspace", "{workspace}"],
        "prompt_style": "positional",
        # model: РІС‹Р±РѕСЂ РјРѕРґРµР»Рё (auto, gpt-5, sonnet-4, sonnet-4-thinking, opus-4)
        # sandbox: enabled|disabled, approve-mcps: bool, browser: bool
        # РќР• РґРѕР±Р°РІР»СЏРµРј allowedTools - СЌС‚Рѕ РќР• СЃС‚Р°РЅРґР°СЂС‚РЅС‹Р№ Р°СЂРіСѓРјРµРЅС‚ Cursor CLI
        "allowed_args": ["model", "sandbox", "approve-mcps", "browser"],
    },
    # cursor_server: DevOps СЂРµР¶РёРј Р‘Р•Р— --force (read-only РґР»СЏ С„Р°Р№Р»РѕРІ)
    # РСЃРїРѕР»СЊР·СѓРµС‚СЃСЏ Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё РґР»СЏ СЃРµСЂРІРµСЂРЅС‹С… Р·Р°РґР°С‡ (target_server_id != null)
    "cursor_server": {
        "command": _cli_command("CURSOR_CLI_PATH", "agent"),
        # РќР•Рў --force: Р°РіРµРЅС‚ РЅРµ РјРѕР¶РµС‚ РјРµРЅСЏС‚СЊ С„Р°Р№Р»С‹ Р»РѕРєР°Р»СЊРЅРѕ
        # --sandbox enabled: РїСЂРёРЅСѓРґРёС‚РµР»СЊРЅР°СЏ РёР·РѕР»СЏС†РёСЏ filesystem
        "args": ["-p", "--output-format", "stream-json", "--stream-partial-output", "--workspace", "{workspace}", "--sandbox", "enabled"],
        "prompt_style": "positional",
        "allowed_args": ["model", "approve-mcps"],
    },
    # cursor_plan: СЂРµР¶РёРј --mode=plan РґР»СЏ Р°РЅР°Р»РёР·Р°/РїР»Р°РЅРёСЂРѕРІР°РЅРёСЏ (СѓС‚РѕС‡РЅСЏСЋС‰РёРµ РІРѕРїСЂРѕСЃС‹)
    # Р”РѕРєСѓРјРµРЅС‚Р°С†РёСЏ: https://cursor.com/ru/docs/cli/overview
    "cursor_plan": {
        "command": _cli_command("CURSOR_CLI_PATH", "agent"),
        "args": ["-p", "--mode=plan"],  # --mode=plan РґР»СЏ РїР»Р°РЅРёСЂРѕРІР°РЅРёСЏ СЃ РІРѕРїСЂРѕСЃР°РјРё
        "prompt_style": "positional",
        "allowed_args": ["model"],
    },
    "claude": {
        "command": _cli_command("CLAUDE_CLI_PATH", "claude"),
        # -p: non-interactive (programmatic) mode
        # --output-format stream-json: СЃС‚СЂРёРјРёРЅРі РґР»СЏ РґРµС‚Р°Р»СЊРЅС‹С… Р»РѕРіРѕРІ
        # --include-partial-messages: РїСЂРѕРјРµР¶СѓС‚РѕС‡РЅС‹Рµ СЃРѕРѕР±С‰РµРЅРёСЏ РїСЂРё СЃС‚СЂРёРјРёРЅРіРµ
        # --dangerously-skip-permissions: РїСЂРѕРїСѓСЃС‚РёС‚СЊ РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ (РґР»СЏ headless)
        # --mcp-config: РїСѓС‚СЊ Рє JSON С„Р°Р№Р»Сѓ СЃ MCP СЃРµСЂРІРµСЂР°РјРё
        # --allowedTools: СЂР°Р·СЂРµС€С‘РЅРЅС‹Рµ РёРЅСЃС‚СЂСѓРјРµРЅС‚С‹ Р±РµР· РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ
        # --model: РІС‹Р±РѕСЂ РјРѕРґРµР»Рё claude (sonnet, opus, haiku)
        # Р”РѕРєСѓРјРµРЅС‚Р°С†РёСЏ: https://docs.anthropic.com/en/docs/claude-code
        # --debug mcp С‚СЂРµР±СѓРµС‚СЃСЏ РґР»СЏ РєРѕСЂСЂРµРєС‚РЅРѕР№ СЂР°Р±РѕС‚С‹ СЃ MCP СЃРµСЂРІРµСЂР°РјРё (Р±РµР· РЅРµРіРѕ CLI Р·Р°РІРёСЃР°РµС‚)
        "args": ["-p", "--verbose", "--output-format", "stream-json", "--include-partial-messages", "--dangerously-skip-permissions", "--debug", "mcp"],
        "prompt_style": "positional",
        "allowed_args": [
            "model",            # Р’С‹Р±РѕСЂ РјРѕРґРµР»Рё Claude
            "mcp-config",       # РџСѓС‚СЊ Рє MCP РєРѕРЅС„РёРіСѓ (РґР»СЏ server_execute Рё РґСЂ.)
            "allowedTools",     # Р Р°Р·СЂРµС€С‘РЅРЅС‹Рµ РёРЅСЃС‚СЂСѓРјРµРЅС‚С‹
            "agent",            # РљР°СЃС‚РѕРјРЅС‹Р№ Р°РіРµРЅС‚
            "continue",         # -c РґР»СЏ РїСЂРѕРґРѕР»Р¶РµРЅРёСЏ СЃРµСЃСЃРёРё
        ],
        "timeout_seconds": 1800,  # 30 РјРёРЅСѓС‚ РґР»СЏ РіР»СѓР±РѕРєРёС… РѕРїРµСЂР°С†РёР№
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# Celery Configuration
# =============================================================================
# Redis URL for Celery broker and result backend
# Format: redis://[:password]@host:port/db_number
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

# Task serialization
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Timezone (use Django's timezone)
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit for graceful shutdown

# Result expiration (24 hours)
CELERY_RESULT_EXPIRES = 60 * 60 * 24

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # For long-running tasks
CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "4"))

# Task routes (optional, for separating queues)
CELERY_TASK_ROUTES = {
    "tasks.tasks.analyze_task_async": {"queue": "analysis"},
    "tasks.tasks.run_workflow_async": {"queue": "workflows"},
    "agent_hub.tasks.*": {"queue": "agents"},
}

