"""
Django settings for web_ui project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import json
import os
import shutil

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@b9idj_4skbcph+21q6^bc0qbs*$qs&@7r2sqfn*1#)z5_i%my'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'core_ui',
    'tasks',
    'passwords',
    'servers',
    'agent_hub',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_ui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core_ui' / 'templates',
            BASE_DIR / 'tasks' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_ui.wsgi.application'
ASGI_APPLICATION = 'web_ui.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'core_ui' / 'static',
]

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
UPLOADED_FILES_DIR = MEDIA_ROOT / 'uploads'

# Create upload directory if it doesn't exist
UPLOADED_FILES_DIR.mkdir(parents=True, exist_ok=True)

# Agent projects directory
AGENT_PROJECTS_DIR = BASE_DIR / 'agent_projects'
AGENT_PROJECTS_DIR.mkdir(parents=True, exist_ok=True)

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# CLI runtime timeout
CLI_RUNTIME_TIMEOUT_SECONDS = int(os.getenv("CLI_RUNTIME_TIMEOUT_SECONDS", "600"))

# Cursor CLI: HTTP/1 mode (default on) to avoid proxy/VPN issues when HTTP/2 is blocked.
# Override: CURSOR_CLI_HTTP_1=0 or false to disable.
_raw_http1 = os.getenv("CURSOR_CLI_HTTP_1", "1").strip().lower()
CURSOR_CLI_HTTP_1 = _raw_http1 not in ("0", "false", "no", "off")


def _parse_cursor_cli_extra_env():
    """Extra env vars for Cursor CLI. When CURSOR_CLI_HTTP_1 is True, adds CURSOR_DISABLE_HTTP2=1.
    Override via CURSOR_CLI_EXTRA_ENV JSON, e.g. CURSOR_CLI_EXTRA_ENV='{"KEY":"VALUE"}'."""
    raw = os.getenv("CURSOR_CLI_EXTRA_ENV", "").strip()
    if raw:
        try:
            d = json.loads(raw)
            return dict(d) if isinstance(d, dict) else {}
        except json.JSONDecodeError:
            return {}
    if CURSOR_CLI_HTTP_1:
        return {"CURSOR_DISABLE_HTTP2": "1"}
    return {}


CURSOR_CLI_EXTRA_ENV = _parse_cursor_cli_extra_env()

# CLI runtime configuration for external agents
def _cli_command(env_var: str, default_name: str) -> str:
    return os.getenv(env_var) or shutil.which(default_name) or default_name


CLI_RUNTIME_CONFIG = {
    "cursor": {
        "command": _cli_command("CURSOR_CLI_PATH", "agent"),
        "args": ["-p", "--output-format", "text", "--workspace", "{workspace}", "--model", "auto"],
        "prompt_style": "positional",
        "allowed_args": [],  # Модель всегда auto, нельзя изменить
    },
    "ralph": {
        "command": _cli_command("RALPH_CLI_PATH", "ralph"),
        "args": ["run", "-p"],
        "prompt_style": "positional",
        "allowed_args": ["backend", "max-iterations", "completion-promise", "no-tui", "continue"],
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
