from django.urls import path
from . import views

app_name = "agent_hub"

urlpatterns = [
    path("", views.agents_page, name="agents_page"),
    path("logs/", views.logs_page, name="logs_page"),
    path("admin/logs/", views.admin_logs_page, name="admin_logs_page"),
    path("admin/api/runs/", views.admin_api_runs_list, name="admin_api_runs_list"),
    path("admin/api/runs/<int:run_id>/status/", views.admin_api_run_status, name="admin_api_run_status"),
    path("admin/api/runs/<int:run_id>/update/", views.admin_api_run_update, name="admin_api_run_update"),
    path("admin/api/runs/<int:run_id>/restart/", views.admin_api_run_restart, name="admin_api_run_restart"),
    path("admin/api/workflows/run/<int:run_id>/status/", views.admin_api_workflow_run_status, name="admin_api_workflow_run_status"),
    path("admin/api/workflows/run/<int:run_id>/update/", views.admin_api_workflow_run_update, name="admin_api_workflow_run_update"),
    path("admin/api/workflows/run/<int:run_id>/restart/", views.admin_api_workflow_run_restart, name="admin_api_workflow_run_restart"),
    path("api/profiles/", views.api_profiles_list, name="api_profiles_list"),
    path("api/profiles/create/", views.api_profiles_create, name="api_profiles_create"),
    path("api/profiles/<int:profile_id>/update/", views.api_profiles_update, name="api_profiles_update"),
    path("api/profiles/<int:profile_id>/delete/", views.api_profiles_delete, name="api_profiles_delete"),
    path("api/profiles/<int:profile_id>/run/", views.api_profile_run, name="api_profile_run"),
    path("api/run/", views.api_agent_run, name="api_agent_run"),
    path("api/runs/", views.api_runs_list, name="api_runs_list"),
    path("api/runs/<int:run_id>/status/", views.api_run_status, name="api_run_status"),
    path("api/runs/<int:run_id>/stop/", views.api_run_stop, name="api_run_stop"),
    path("api/runs/<int:run_id>/delete/", views.api_run_delete, name="api_run_delete"),
    path("api/assist-config/", views.api_assist_config, name="api_assist_config"),
    path("api/projects/", views.api_projects_list, name="api_projects_list"),
    path("api/projects/create/", views.api_projects_create, name="api_projects_create"),
    path("api/workflows/", views.api_workflows_list, name="api_workflows_list"),
    path("api/workflows/import/", views.api_workflow_import, name="api_workflow_import"),
    path("api/workflows/<int:workflow_id>/", views.api_workflow_get, name="api_workflow_get"),
    path("api/workflows/<int:workflow_id>/update/", views.api_workflow_update, name="api_workflow_update"),
    path("api/workflows/<int:workflow_id>/delete/", views.api_workflow_delete, name="api_workflow_delete"),
    path("api/workflows/generate/", views.api_workflow_generate, name="api_workflow_generate"),
    path("api/workflows/from-task/", views.api_workflow_from_task, name="api_workflow_from_task"),
    path("api/workflows/create-manual/", views.api_workflow_create_manual, name="api_workflow_create_manual"),
    path("api/tasks/generate/", views.api_tasks_generate, name="api_tasks_generate"),
    path("api/workflows/run/", views.api_workflow_run, name="api_workflow_run"),
    path("api/workflows/run/<int:run_id>/status/", views.api_workflow_run_status, name="api_workflow_run_status"),
    path("api/workflows/run/<int:run_id>/stop/", views.api_workflow_stop, name="api_workflow_stop"),
    path("api/workflows/run/<int:run_id>/restart/", views.api_workflow_restart, name="api_workflow_restart"),
    path("api/workflows/run/<int:run_id>/skip/", views.api_workflow_skip_step, name="api_workflow_skip_step"),
    path("api/workflows/run/<int:run_id>/skip-step/", views.api_workflow_skip_specific_step, name="api_workflow_skip_specific_step"),
    path("api/workflows/run/<int:run_id>/continue/", views.api_workflow_continue, name="api_workflow_continue"),
    path("api/workflows/run/<int:run_id>/retry/", views.api_workflow_retry_step, name="api_workflow_retry_step"),
    path("api/workflows/run/<int:run_id>/delete/", views.api_workflow_run_delete, name="api_workflow_run_delete"),
    path("api/workflows/<int:workflow_id>/download/", views.api_workflow_download_project, name="api_workflow_download_project"),
    path("api/assist-auto/", views.api_assist_auto, name="api_assist_auto"),
    path("api/mcp/servers/", views.api_mcp_servers, name="api_mcp_servers"),
    path("api/mcp/servers/connect/", views.api_mcp_server_connect, name="api_mcp_server_connect"),
    path("api/mcp/servers/disconnect/", views.api_mcp_server_disconnect, name="api_mcp_server_disconnect"),
    path("api/mcp/servers/tools/", views.api_mcp_server_tools, name="api_mcp_server_tools"),
    # Model selection and smart analysis
    path("api/models/", views.api_list_models, name="api_list_models"),
    path("api/smart-analyze/", views.api_smart_analyze, name="api_smart_analyze"),
    # Custom Agents
    path("custom-agents/", views.custom_agents_view, name="custom_agents"),
    path("api/custom-agents/", views.api_custom_agents_list, name="api_custom_agents_list"),
    path("api/custom-agents/<int:agent_id>/", views.api_custom_agent_detail, name="api_custom_agent_detail"),
    path("api/custom-agents/<int:agent_id>/export/", views.api_custom_agent_export, name="api_custom_agent_export"),
]
