# Generated by Django 5.2.10 on 2026-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_hub', '0003_agent_workflows'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentprofile',
            new_name='agent_hub_a_owner_i_c90a7e_idx',
            old_name='agent_hub__owner_i_7a6a0f_idx',
        ),
        migrations.RenameIndex(
            model_name='agentprofile',
            new_name='agent_hub_a_agent_t_83e581_idx',
            old_name='agent_hub__agent_t_a28589_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agent_hub_a_runtime_16d71a_idx',
            old_name='agent_hub__runtime_c_05111d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='agent_hub_a_status_7f69d3_idx',
            old_name='agent_hub__status_c_a60811_idx',
        ),
        migrations.AddField(
            model_name='agentworkflow',
            name='project_path',
            field=models.CharField(blank=True, help_text='Путь к папке проекта (относительно agent_projects)', max_length=500),
        ),
        migrations.AlterField(
            model_name='agentpreset',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='internal', max_length=20),
        ),
    ]
