# Generated by Django 5.2.10 on 2026-01-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_hub', '0007_add_log_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='mcp_auto_approve',
            field=models.BooleanField(default=False, help_text='Автоматически одобрять MCP инструменты без подтверждения'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='mcp_servers',
            field=models.JSONField(blank=True, default=dict, help_text='MCP серверы для этого агента (per-agent isolation)'),
        ),
        migrations.AlterField(
            model_name='agentpreset',
            name='agent_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex'), ('react', 'ReAct'), ('ralph', 'Ralph Wiggum'), ('claude_code', 'Claude Code')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentpreset',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex'), ('react', 'ReAct'), ('ralph', 'Ralph Wiggum'), ('claude_code', 'Claude Code')], default='react', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentworkflow',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='gemini', max_length=20),
        ),
    ]
