# Generated by Django 5.2.10 on 2026-01-31 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_hub', '0008_add_mcp_per_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(default='Ты DevOps агент, специализирующийся на автоматизации задач.', help_text='Базовый промпт агента (роль, инструкции)')),
                ('instructions', models.TextField(blank=True, help_text='Дополнительные инструкции для агента')),
                ('allowed_tools', models.JSONField(blank=True, default=list, help_text='Список разрешённых инструментов (ssh_execute, read_file, etc)')),
                ('max_iterations', models.IntegerField(default=5, help_text='Максимальное количество итераций для ReAct/Ralph')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature для LLM (0.0 - 1.0)')),
                ('completion_promise', models.CharField(default='COMPLETE', help_text='Фраза для завершения (для Ralph mode)', max_length=100)),
                ('runtime', models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='claude', help_text='CLI runtime для выполнения', max_length=20)),
                ('model', models.CharField(default='claude-4.5-sonnet', help_text='Модель для использования', max_length=50)),
                ('orchestrator_mode', models.CharField(choices=[('react', 'ReAct Loop'), ('ralph_internal', 'Ralph Internal'), ('ralph_cli', 'Ralph CLI')], default='ralph_internal', help_text='Режим оркестратора', max_length=20)),
                ('mcp_servers', models.JSONField(blank=True, default=dict, help_text='MCP серверы для этого агента')),
                ('mcp_auto_approve', models.BooleanField(default=False, help_text='Автоматически одобрять MCP инструменты')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли агент другим пользователям')),
                ('usage_count', models.IntegerField(default=0, help_text='Количество использований')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='agent_hub_c_owner_i_704f54_idx'), models.Index(fields=['is_active', 'is_public'], name='agent_hub_c_is_acti_5d062b_idx')],
            },
        ),
    ]
