# Generated by Django 5.2 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('agent_hub', '0010_add_agent_servers_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customagent',
            name='skills',
            field=models.ManyToManyField(
                blank=True,
                help_text='Skills, которые будут автоматически добавляться в prompt этого агента',
                related_name='bound_custom_agents',
                to='skills.skill',
            ),
        ),
    ]
