# Generated by Django 5.2 on 2026-02-04

import agent_hub.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_hub', '0011_add_custom_agent_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='generic', max_length=50)),
                ('secret', models.CharField(db_index=True, default=agent_hub.models._generate_webhook_secret, max_length=64, unique=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('agent_type', models.CharField(default='react', help_text='Fallback agent type if custom_agent is not set', max_length=50)),
                ('auto_execute', models.BooleanField(default=True)),
                ('execution_mode', models.CharField(choices=[('task', 'Task'), ('workflow', 'Workflow')], default='task', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_triggers', to='agent_hub.customagent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [
                    models.Index(fields=['owner', '-updated_at'], name='agent_hub_aw_owner_upd_idx'),
                    models.Index(fields=['source'], name='agent_hub_aw_source_idx'),
                    models.Index(fields=['is_active'], name='agent_hub_aw_active_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AgentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_hub.agentwebhook')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='agent_hub_awe_status_idx'),
                    models.Index(fields=['webhook', '-created_at'], name='agent_hub_awe_webhook_idx'),
                ],
            },
        ),
    ]
