# Generated by Django 5.2.10 on 2026-02-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_hub', '0012_add_agent_webhooks'),
        ('tasks', '0016_add_workflow_task_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentwebhook',
            new_name='agent_hub_a_owner_i_844770_idx',
            old_name='agent_hub_aw_owner_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='agentwebhook',
            new_name='agent_hub_a_source_fe9187_idx',
            old_name='agent_hub_aw_source_idx',
        ),
        migrations.RenameIndex(
            model_name='agentwebhook',
            new_name='agent_hub_a_is_acti_57f5fa_idx',
            old_name='agent_hub_aw_active_idx',
        ),
        migrations.RenameIndex(
            model_name='agentwebhookevent',
            new_name='agent_hub_a_status_4d0a89_idx',
            old_name='agent_hub_awe_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentwebhookevent',
            new_name='agent_hub_a_webhook_e15c9c_idx',
            old_name='agent_hub_awe_webhook_idx',
        ),
        migrations.AddField(
            model_name='agentworkflow',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Задача, из которой создан workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='agentpreset',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('codex', 'Codex CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('codex', 'Codex CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('codex', 'Codex CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentworkflow',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('codex', 'Codex CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='customagent',
            name='runtime',
            field=models.CharField(choices=[('internal', 'Internal'), ('cursor', 'Cursor CLI'), ('claude', 'Claude Code CLI'), ('codex', 'Codex CLI'), ('opencode', 'OpenCode CLI'), ('gemini', 'Gemini CLI'), ('ralph', 'Ralph Orchestrator')], default='claude', help_text='CLI runtime для выполнения', max_length=20),
        ),
    ]
