# Generated by Django 5.2.10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('tasks', '0002_taskattachment_taskcomment_taskhistory_tasklabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_ai',
            field=models.BooleanField(default=False, help_text='Назначена ли задача на ИИ'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_agent_type',
            field=models.CharField(blank=True, help_text='Тип агента для выполнения (react, simple, complex, ralph)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_execution_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Ожидает выполнения'), ('ANALYZING', 'Анализируется'), ('PLANNING', 'Планируется'), ('EXECUTING', 'Выполняется'), ('COMPLETED', 'Завершена'), ('FAILED', 'Ошибка'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='target_server',
            field=models.ForeignKey(blank=True, help_text='Сервер, на котором нужно выполнить задачу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='servers.server'),
        ),
        migrations.AddField(
            model_name='task',
            name='server_name_mentioned',
            field=models.CharField(blank=True, help_text='Название сервера, упомянутое в описании задачи', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration_hours',
            field=models.FloatField(blank=True, help_text='Оценка времени выполнения в часах', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_duration_hours',
            field=models.FloatField(blank=True, help_text='Фактическое время выполнения в часах', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_execution_suggested',
            field=models.BooleanField(default=False, help_text='Предложено ли автоматическое выполнение'),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_execution_approved',
            field=models.BooleanField(default=False, help_text='Одобрено ли автоматическое выполнение'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to_ai', 'ai_execution_status'], name='tasks_task_assigne_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['target_server', 'status'], name='tasks_task_target__idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='tasks_task_due_dat_idx'),
        ),
    ]
