# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_add_ai_and_server_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, help_text='Детальное описание подзадачи'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок выполнения подзадачи'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='estimated_duration_minutes',
            field=models.IntegerField(
                blank=True,
                help_text='Оценка времени выполнения в минутах',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='subtask',
            name='actual_duration_minutes',
            field=models.IntegerField(
                blank=True,
                help_text='Фактическое время выполнения в минутах',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='subtask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Срок выполнения подзадачи', null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='assigned_to_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='execution_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Ожидает'),
                    ('IN_PROGRESS', 'Выполняется'),
                    ('COMPLETED', 'Завершена'),
                    ('FAILED', 'Ошибка'),
                    ('BLOCKED', 'Заблокирована'),
                ],
                default='PENDING',
                max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'order'], name='tasks_subta_task_id_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'is_completed'], name='tasks_subta_task_id_comp_idx'),
        ),
    ]
