# Generated by Django 5.2.10 on 2026-01-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_subtask_add_description_and_related'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(help_text='Тип агента, выполняющего задачу', max_length=50)),
                ('execution_plan', models.JSONField(blank=True, help_text='План выполнения задачи', null=True)),
                ('execution_log', models.TextField(blank=True, help_text='Лог выполнения')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ANALYZING', 'Анализируется'), ('PLANNING', 'Планируется'), ('EXECUTING', 'Выполняется'), ('COMPLETED', 'Завершена'), ('FAILED', 'Ошибка'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True, help_text='Краткое описание результата')),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке, если есть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('AUTO_EXECUTION_SUGGESTION', 'Предложение автоматического выполнения'), ('TASK_OVERDUE', 'Просрочка задачи'), ('SUBTASK_OVERDUE', 'Просрочка подзадачи'), ('EXECUTION_STARTED', 'Начато выполнение'), ('EXECUTION_COMPLETED', 'Выполнение завершено'), ('EXECUTION_FAILED', 'Ошибка выполнения'), ('SERVER_DETECTED', 'Обнаружен сервер в задаче')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_data', models.JSONField(blank=True, help_text='Данные для действия (например, server_id для подключения)', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL для действия', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False, help_text='Было ли выполнено действие')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RenameIndex(
            model_name='subtask',
            new_name='tasks_subta_task_id_7abf4d_idx',
            old_name='tasks_subta_task_id_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='subtask',
            new_name='tasks_subta_task_id_909610_idx',
            old_name='tasks_subta_task_id_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_assigne_8552a8_idx',
            old_name='tasks_task_assigne_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_target__d58cfa_idx',
            old_name='tasks_task_target__idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_3f7773_idx',
            old_name='tasks_task_due_dat_idx',
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.subtask'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task', '-created_at'], name='tasks_taske_task_id_1b50b0_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status', '-created_at'], name='tasks_taske_status_8a3200_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='tasks_taskn_user_id_6cafba_idx'),
        ),
        migrations.AddIndex(
            model_name='tasknotification',
            index=models.Index(fields=['task', '-created_at'], name='tasks_taskn_task_id_ac7e7d_idx'),
        ),
    ]
