# Generated by Django 5.2.10 on 2026-01-28 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_add_task_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDelegatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_ui', models.CharField(choices=[('chat', 'Чат с контекстом задачи'), ('task_form', 'Форма задачи агента')], default='chat', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка делегирования ИИ',
                'verbose_name_plural': 'Настройки делегирования ИИ',
            },
        ),
    ]
