# Generated by Django 5.2.10 on 2026-01-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_servergroup_advanced'),
        ('tasks', '0007_add_user_delegate_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknotification',
            name='notification_type',
            field=models.CharField(choices=[('AUTO_EXECUTION_SUGGESTION', 'Предложение автоматического выполнения'), ('SERVER_CONFIRMATION', 'Подтверждение сервера'), ('QUESTIONS_REQUIRED', 'Требуются уточнения'), ('TASK_OVERDUE', 'Просрочка задачи'), ('SUBTASK_OVERDUE', 'Просрочка подзадачи'), ('EXECUTION_STARTED', 'Начато выполнение'), ('EXECUTION_COMPLETED', 'Выполнение завершено'), ('EXECUTION_FAILED', 'Ошибка выполнения'), ('SERVER_DETECTED', 'Обнаружен сервер в задаче'), ('INFO', 'Информация'), ('WARNING', 'Предупреждение')], max_length=50),
        ),
        migrations.CreateModel(
            name='TaskExecutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_server_confirmation', models.BooleanField(default=True, help_text='Требовать подтверждение сервера перед выполнением задачи')),
                ('auto_execute_simple_tasks', models.BooleanField(default=False, help_text='Автоматически выполнять простые задачи без подтверждения')),
                ('ask_questions_before_execution', models.BooleanField(default=True, help_text='Задавать уточняющие вопросы перед выполнением, если информации недостаточно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_server', models.ForeignKey(blank=True, help_text='Сервер по умолчанию для выполнения задач (если не указан другой)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='servers.server')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_execution_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки выполнения задач',
                'verbose_name_plural': 'Настройки выполнения задач',
            },
        ),
    ]
