# Generated by Django 5.2.10 on 2026-01-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_task_execution_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID задачи во внешней системе (например DEVOPS-123)', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='external_system',
            field=models.CharField(choices=[('jira', 'Jira'), ('github', 'GitHub Issues'), ('gitlab', 'GitLab Issues'), ('internal', 'Internal')], default='internal', help_text='Внешняя система, из которой импортирована задача', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='external_url',
            field=models.URLField(blank=True, help_text='Прямая ссылка на задачу во внешней системе'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Время последней синхронизации с внешней системой', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sync_back',
            field=models.BooleanField(default=True, help_text='Синхронизировать статус обратно во внешнюю систему'),
        ),
    ]
