# Generated by Django 5.2.10 on 2026-02-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_add_custom_agent_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ai_agent_type',
            field=models.CharField(blank=True, help_text='Тип агента для выполнения (react, simple, complex, ralph) — используется если recommended_custom_agent не задан', max_length=50, null=True),
        ),
    ]
