# Generated by Django 5.2.10 on 2026-02-04 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_hub', '0010_add_agent_servers_knowledge'),
        ('servers', '0006_add_projects_sprints_materials'),
        ('tasks', '0011_alter_task_ai_agent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('blocks', 'Блокирует'), ('blocked_by', 'Заблокирована'), ('relates_to', 'Связана с'), ('duplicates', 'Дублирует'), ('duplicated_by', 'Дублируется')], default='relates_to', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Связь задач',
                'verbose_name_plural': 'Связи задач',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='tasks.task', verbose_name='Родительская задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_key',
            field=models.CharField(blank=True, db_index=True, help_text='Автогенерируемый ключ (WEU-123)', max_length=20, verbose_name='Ключ задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('key', models.CharField(help_text='Короткий ключ проекта (например: WEU, DEV). Используется в ID задач.', max_length=10, unique=True, verbose_name='Ключ')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, help_text='Видимость для всех пользователей системы', verbose_name='Публичный')),
                ('color', models.CharField(default='#3B82F6', help_text='HEX цвет проекта', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(default='folder', max_length=50, verbose_name='Иконка')),
                ('task_counter', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Архивирован')),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_assignee_projects', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель по умолчанию')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Для приглашения по email', max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('member', 'Участник'), ('viewer', 'Наблюдатель')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Персональное сообщение')),
                ('token', models.CharField(help_text='Для принятия по ссылке', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tasks.project')),
                ('user', models.ForeignKey(blank=True, help_text='Если уже зарегистрирован', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_invitations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приглашение в проект',
                'verbose_name_plural': 'Приглашения в проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('material_type', models.CharField(choices=[('document', 'Документ'), ('link', 'Ссылка'), ('file', 'Файл'), ('wiki', 'Wiki-страница')], max_length=20, verbose_name='Тип')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_materials/%Y/%m/', verbose_name='Файл')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('content', models.TextField(blank=True, help_text='Markdown', verbose_name='Содержимое')),
                ('folder', models.CharField(blank=True, max_length=200, verbose_name='Папка')),
                ('pinned', models.BooleanField(default=False, verbose_name='Закреплён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Материал проекта',
                'verbose_name_plural': 'Материалы проектов',
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('member', 'Участник'), ('viewer', 'Наблюдатель')], default='member', max_length=20)),
                ('notify_on_new_task', models.BooleanField(default=True, verbose_name='Уведомлять о новых задачах')),
                ('notify_on_mention', models.BooleanField(default=True, verbose_name='Уведомлять об упоминаниях')),
                ('notify_on_assignment', models.BooleanField(default=True, verbose_name='Уведомлять о назначениях')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('filter_config', models.JSONField(help_text='{"status": ["TODO"], "assignee": [1,2], "priority": ["HIGH"]}', verbose_name='Конфигурация фильтра')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='tasks.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_task_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохранённый фильтр',
                'verbose_name_plural': 'Сохранённые фильтры',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('goal', models.TextField(blank=True, verbose_name='Цель спринта')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('active', 'Активный'), ('completed', 'Завершён')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринты',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.sprint', verbose_name='Спринт'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_task_project_b78682_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'sprint'], name='tasks_task_project_64d6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_key'], name='tasks_task_task_ke_502574_idx'),
        ),
        migrations.AddField(
            model_name='taskrelation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrelation',
            name='from_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskrelation',
            name='to_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-updated_at'], name='tasks_proje_owner_i_f6a2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['key'], name='tasks_proje_key_145595_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['email', 'status'], name='tasks_proje_email_34c27d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['token'], name='tasks_proje_token_53cb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project', 'status'], name='tasks_proje_project_fcb244_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmaterial',
            index=models.Index(fields=['project', '-pinned', '-updated_at'], name='tasks_proje_project_a8e7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmaterial',
            index=models.Index(fields=['project', 'material_type'], name='tasks_proje_project_aa0f74_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'project'], name='tasks_proje_user_id_c302c1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'role'], name='tasks_proje_project_8d0857_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='savedfilter',
            index=models.Index(fields=['user', 'project'], name='tasks_saved_user_id_89b897_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', 'status'], name='tasks_sprin_project_64ee46_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', '-start_date'], name='tasks_sprin_project_3752eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskrelation',
            unique_together={('from_task', 'to_task', 'relation_type')},
        ),
    ]
