# Generated by Django 5.2.10 on 2026-02-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_add_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_execution_report',
            field=models.JSONField(blank=True, help_text='Структурированный отчёт о выполнении (команды, ошибки, находки)', null=True),
        ),
        migrations.AlterField(
            model_name='tasknotification',
            name='notification_type',
            field=models.CharField(choices=[('AUTO_EXECUTION_SUGGESTION', 'Предложение автоматического выполнения'), ('SERVER_CONFIRMATION', 'Подтверждение сервера'), ('QUESTIONS_REQUIRED', 'Требуются уточнения'), ('TASK_OVERDUE', 'Просрочка задачи'), ('SUBTASK_OVERDUE', 'Просрочка подзадачи'), ('EXECUTION_STARTED', 'Начато выполнение'), ('EXECUTION_COMPLETED', 'Выполнение завершено'), ('EXECUTION_FAILED', 'Ошибка выполнения'), ('SERVER_DETECTED', 'Обнаружен сервер в задаче'), ('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('PROJECT_INVITATION', 'Приглашение в проект'), ('PROJECT_ROLE_CHANGED', 'Изменение роли в проекте'), ('PROJECT_MEMBER_JOINED', 'Новый участник проекта'), ('PROJECT_MEMBER_LEFT', 'Участник покинул проект'), ('TASK_ASSIGNED', 'Задача назначена'), ('TASK_MENTIONED', 'Упоминание в задаче'), ('TASK_WATCHING', 'Обновление отслеживаемой задачи'), ('TASK_MOVED', 'Задача перемещена'), ('STATUS_CHANGED', 'Изменение статуса задачи'), ('SPRINT_STARTED', 'Спринт начат'), ('SPRINT_ENDING', 'Спринт заканчивается'), ('SPRINT_COMPLETED', 'Спринт завершён')], max_length=50),
        ),
    ]
