# Generated by Django 5.2 on 2026-02-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('staging', 'Staging'), ('prod', 'Production')], default='draft', max_length=20)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('rules', models.TextField(blank=True, default='')),
                ('references', models.JSONField(blank=True, default=list, help_text='Список объектов вида {"title": "...", "content": "..."}')),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('allowed_runtimes', models.JSONField(blank=True, default=list, help_text='Пусто = для всех runtime, иначе список: ["cursor", "claude", ...]')),
                ('auto_apply_chat', models.BooleanField(default=False)),
                ('auto_apply_agents', models.BooleanField(default=False)),
                ('auto_apply_workflows', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('git', 'Git')], default='manual', max_length=20)),
                ('source_url', models.CharField(blank=True, default='', max_length=600)),
                ('source_ref', models.CharField(blank=True, default='main', max_length=120)),
                ('source_path', models.CharField(blank=True, default='SKILL.md', help_text='Файл или папка внутри репозитория (например SKILL.md или skills/devops)', max_length=400)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='null = глобальный корпоративный skill', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'is_active', 'status'], name='skills_skil_owner_i_28af85_idx'), models.Index(fields=['auto_sync_enabled', 'last_synced_at'], name='skills_skil_auto_sy_6287ca_idx'), models.Index(fields=['updated_at'], name='skills_skil_updated_7e19ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'slug'), name='skills_unique_owner_slug'), models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='skills_unique_global_slug')],
            },
        ),
        migrations.CreateModel(
            name='SkillSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='skills.skill')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['skill', '-created_at'], name='skills_skil_skill_i_54b753_idx')],
            },
        ),
    ]
