# Generated by Django 6.0.1 on 2026-02-04 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_skill_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_skills', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='skills.skill')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['shared_with', '-updated_at'], name='skills_skil_shared__a90912_idx'), models.Index(fields=['skill', '-updated_at'], name='skills_skil_skill_i_9e3414_idx')],
                'constraints': [models.UniqueConstraint(fields=('skill', 'shared_with'), name='skills_unique_share_per_user')],
            },
        ),
    ]
