# Generated by Django 5.2.10 on 2026-02-18 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_server_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальный идентификатор сервера (например filesystem)', max_length=120)),
                ('command', models.CharField(max_length=300)),
                ('args', models.JSONField(blank=True, default=list, help_text="Список аргументов команды, например ['-y', '@modelcontextprotocol/server-filesystem', '/workspace']")),
                ('env', models.JSONField(blank=True, default=dict, help_text='Переменные окружения, например {"GITHUB_PERSONAL_ACCESS_TOKEN": ""}')),
                ('description', models.TextField(blank=True, default='')),
                ('source_url', models.CharField(blank=True, default='', help_text='Откуда установлен (каталог, репо)', max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mcp_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='skills_user_user_id_72499a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='skills_user_mcp_unique_user_name')],
            },
        ),
    ]
